name: 'action-github-app-token'
description: 'Check out getsentry'
author: 'sentry.io'
inputs:
  private_key:
    description: 'Private key for the GitHub App'
outputs:
  token:
    description: 'Github Token for App installation'
runs:
  using: 'node12'
  main: 'dist/index.js'
